# 포트 설정
server:
  port: 9999

spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
  data:
    mongodb:
      uri: mongodb+srv://banzzac:banzzac@cluster0.34nxdix.mongodb.net/message?retryWrites=true&w=majority
#      uri: mongodb+srv://banzzac:banzzac@cluster0.ergif.mongodb.net/BANZZAC?retryWrites=true&w=majority


#데이터베이스 이름 : message
#유저 ID : banzzac
#유저 password : banzzac
#클러스터이름 : cluster0

#spring:
#  application:
    # serviceId
#    name: message-server

#eureka:
#  instance:
    # 도메인네임 및 하위 서브도메인 이름 설정
#    hostname: message-server.banzzac.com
#  client:
    # message server의 registry에 등록할지 여부
#    register-with-eureka: false
    # message server에 있는 정보들을 가지고 올지 여부
#    fetch-registry: false
#    service-url:
#      defaultZone: http://${message.instance.hostname}:${server.port}/message/

---
#Local Profile Config

---
#Develop Profile Config

